import {STEPS,MODELS,blank,xp,rank,preferred,fit,complete,briefing,publicLink,esc,BASE} from './mission.mjs';
import {zahSodaPop} from './sodapop.mjs';
const $=s=>document.querySelector(s);
export function mountGame({toast,paused,handoff,go,onClear}){
 const key='zah-atlas-mission-v3';let state=blank(),modelIndex=1,rewardTimer;
 try {const saved=JSON.parse(localStorage.getItem(key));if(saved?.version===3&&saved.answers&&Array.isArray(saved.done)&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<=7&&saved.done.every(i=>Number.isInteger(i)&&i>=0&&i<7))state=saved;}catch{}
 const inbound=new URLSearchParams(location.search).get('ref');if(inbound&&/^[a-zA-Z0-9-]{1,28}$/.test(inbound))state.ref=inbound;
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));$('#game-save').textContent='Saved on this device · nothing sent'}catch{$('#game-save').textContent='Session only · storage unavailable'}};
 const first=()=>state.answers.first||'you';
 const field=(name,label,type='text',required=false,placeholder='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" maxlength="120" value="'+esc(state.answers[name])+'" '+(required?'required':'')+' placeholder="'+esc(placeholder)+'" '+(name==='email'?'autocomplete="email"':name==='first'?'autocomplete="given-name"':name==='last'?'autocomplete="family-name"':name==='phone'?'autocomplete="tel"':'')+'></label>';
 const select=(name,label,options,required=true)=>'<label>'+label+'<select name="'+name+'" '+(required?'required':'')+'><option value="">Choose an option</option>'+options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return '<option value="'+esc(v)+'" '+(state.answers[name]===v?'selected':'')+'>'+esc(l)+'</option>'}).join('')+'</select></label>';
 function choices(name,label,options){return '<fieldset class="field-group"><legend>'+label+'</legend><div class="choices">'+options.map(o=>{const [v,l,symbol]=Array.isArray(o)?o:[o,o,''];return '<label class="choice"><input type="radio" name="'+name+'" value="'+esc(v)+'" '+(state.answers[name]===v?'checked':'')+'>'+(symbol?'<b>'+symbol+'</b>':'')+'<span>'+esc(l)+'</span></label>'}).join('')+'</div></fieldset>'}
 function profile(){return '<div class="form-grid">'+field('first','First name *','text',true,'Your first name')+field('last','Last name *','text',true,'Your last name')+field('company','Company *','text',true,'Company or organization')+field('email','Work email *','email',true,'you@company.com')+select('role','Your role *',['Owner / executive','Fleet manager','Site / operations manager','Engineer / technical evaluator','Purchasing / procurement','Operator','Other'])+field('region','City, state & country *','text',true,'Atlanta, GA, United States')+'</div><p class="form-hint">This is a working demonstration. Use fictional details to explore. Information stays on this device; no email or SMS is sent.</p>'}
 function site(){return choices('application','Choose your mission',['Construction','Abrasive blasting','Utilities / cable','Rental fleet','Industrial work','Other'])+'<div class="form-grid">'+select('flow','Airflow needed *',[['110','Up to 110 cfm'],['189','111–189 cfm'],['400','190–400 cfm'],['above400','More than 400 cfm'],['unknown','Not sure — help me size it']])+select('pressure','Working pressure *',[['100','Up to 100 psi'],['150','Up to 150 psi'],['above150','Above 150 psi'],['unknown','Not sure']])+select('power','Power at the site *',['Diesel suitable','Electric required','Open to either','Not sure'])+field('tools','Tools / simultaneous demand','text',false,'E.g. two breakers, intermittent use')+'</div>'}
 function team(){return '<div class="buying-chain"><span><b>◎</b>'+esc(first())+'</span><i>→</i><span><b>⌘</b>Technical review</span><i>→</i><span><b>◈</b>Budget approval</span><i>→</i><span><b>✓</b>Purchasing</span></div>'+choices('authority','Your role in the decision',['I decide','I recommend','I evaluate','I operate','We decide together','Exploring for now'])+'<div class="form-grid">'+field('manager','Who do you report to? / role','text',false,'Name or role, if known')+field('evaluator','Technical evaluator / role','text',false,'Name or role, if known')+field('approver','Final budget approver / role','text',false,'Name or role, if known')+select('purchasing','Who places the order? *',['My company directly','Central procurement','Dealer / distributor','Rental provider','To be confirmed'])+field('partner','Current dealer or rental partner','text',false,'Optional')+'</div><p class="form-hint">Unknown names are okay. The brief flags missing stakeholders for the rep to clarify.</p>'}
 function plan(){return choices('intent','Choose your path',[['Buy','Build the fleet','◈'],['Rent','Cover the project','↗'],['Compare','Compare the options','⇄']])+'<div class="form-grid">'+select('timeframe','When do you need it? *',['Within 30 days','1–3 months','3–6 months','6+ months','Exploring'])+select('budget','Budget band *',['Under $25,000','$25,000–$50,000','$50,000–$100,000','$100,000+','Rental budget to confirm','Not set yet'])+select('priority','What matters most? *',['Uptime / reliability','Capacity','Portability','Operating cost','Lower site emissions','Flexibility'])+field('current','Current equipment / challenge','text',false,'Optional')+'</div><div class="game-tip"><b>◈</b><span>'+esc(first())+', your '+esc(state.answers.application||'jobsite')+' mission earns the same progress at every budget. The right fit is the win.</span></div>'}
 function visit(){const a=state.answers;return choices('visit','What kind of walkthrough would help?',[['On site','At our site','⌖'],['Virtual','Video call','▣'],['Later','Discuss later','◷']])+'<div id="visit-fields" class="form-grid" '+(!a.visit||a.visit==='Later'?'hidden':'')+'>'+field('date','Preferred date *','date',false)+select('slot','Time window *',['Morning, 8–12','Afternoon, 12–5','Flexible'],false)+select('timezone','Time zone *',['US Eastern','US Central','US Mountain','US Pacific','Other — see notes'],false)+field('site','Site / city (required for on-site)','text',false,'Where would we meet?')+field('attendees','Who should attend?','text',false,'You, technical lead, approver…')+field('visitGoal','What would you like to see?','text',false,'Tools, noise, maintenance, sizing…')+'</div><p class="form-hint">A preferred window starts the conversation. Availability must be confirmed by a person.</p><div class="form-grid">'+select('contact','Preferred follow-up *',['Email','Phone','SMS'])+field('phone','Phone (if phone / SMS selected)','tel',false,'Include country code')+'<label class="checkbox full"><input type="checkbox" name="sms" value="yes" '+(a.sms==='yes'?'checked':'')+'>I would allow SMS about this request. This demo sends nothing.</label><label class="checkbox full"><input type="checkbox" name="marketing" value="yes" '+(a.marketing==='yes'?'checked':'')+'>I would also like relevant equipment updates by email. Optional.</label></div>'}
 function referrals(){return choices('referral','How would you like to connect?',[['Invite teammate','Invite my buying team','⌘'],['Refer another business','Refer a business','↗'],['Referred by someone','Someone referred me','◈'],['Continue solo','Continue on my own','◎']])+'<div class="form-grid">'+field('referralContext','Referral context (optional)','text',false,'Company or referrer; no private contact details')+'<label class="full">Anything else your rep should know?<textarea name="notes" maxlength="500" placeholder="Site access, timing, questions…">'+esc(state.answers.notes)+'</textarea></label></div><div class="game-tip"><b>↗</b><span>Your next screen unlocks an invitation link, a personal brief and a local sales record. You choose what to share. A production referral incentive would need program terms; no reward is promised in this demo.</span></div>'}
 function updateMap(){const points=xp(state);$('#live-xp').innerHTML='LEVEL '+(points<250?'01':points<600?'02':points<1000?'03':'04')+'<b>'+points.toLocaleString()+' XP</b>';$('#xp-total').textContent=points.toLocaleString()+' / 1,000 XP';$('#badge-count').textContent=state.done.length+' / 7';$('#xp-fill').style.width=points/10+'%';$('#xp-ring').style.strokeDashoffset=327*(1-points/1000);$('#player-name').textContent=state.answers.first?state.answers.first+"'s mission":'Your mission starts here.';$('#rank-name').textContent=rank(state);$('#rank-number').textContent=String(points<250?1:points<600?2:points<1000?3:4).padStart(2,'0');
 $('#mission-map').innerHTML=STEPS.map((s,i)=>'<li><button type="button" data-step="'+i+'" class="'+(state.step===i?'current ':state.done.includes(i)?'complete':'')+'" '+(i>state.step&&!state.done.includes(i)?'disabled':'')+' aria-label="'+esc(s.label)+(state.done.includes(i)?', completed':'')+'"><span>'+(state.done.includes(i)?'✓':i+1)+'</span><span>'+s.label+'<small>'+s.badge+'</small></span></button></li>').join('')}
 function collect(){const f=$('#mission-form');if(!f)return {};const a=Object.fromEntries(new FormData(f));if(state.step===5){a.sms=f.elements.sms.checked?'yes':'no';a.marketing=f.elements.marketing.checked?'yes':'no'}return a}
 function focusStage(){const main=$('#zw-main'),el=$('.stage-top'),m=main.getBoundingClientRect(),r=el.getBoundingClientRect();main.scrollTo({top:main.scrollTop+r.top-m.top-85,behavior:paused()?'auto':'smooth'})}
 function celebrate(i){clearTimeout(rewardTimer);const s=STEPS[i],host=$('#achievement');host.innerHTML='<div class="reward-card"><span class="reward-icon">'+(i===6?'✦':'◈')+'</span><small>ACHIEVEMENT UNLOCKED</small><strong>'+esc(s.badge)+'</strong><p>+'+s.xp+' XP · '+esc(first())+', '+(i===6?'your mission is ready.':'next move unlocked.')+'</p></div>';const el=host.firstElementChild;
 if(!paused()){el.animate([{transform:'translateY(-25px) scale(.8)',opacity:0},{transform:'translateY(5px) scale(1.04)',opacity:1},{transform:'none',opacity:1}],{duration:500,easing:'cubic-bezier(.16,1,.3,1)'});zahSodaPop(el,true)}
 rewardTimer=setTimeout(()=>host.replaceChildren(),3400);
 }
 function render(){updateMap();const i=state.step;if(i===7){result();return}const s=STEPS[i];$('#stage-eyebrow').textContent='CHALLENGE 0'+(i+1)+' / '+s.label.toUpperCase();$('#stage-reward').textContent=state.done.includes(i)?'✓ ACHIEVEMENT EARNED':'＋'+s.xp+' XP';
 $('#game-stage').innerHTML='<div class="game-heading"><h3>'+s.title+'</h3><p>'+esc(i===2?first()+', compare your next machine. Swipe or use the arrows.':s.sub)+'</p></div><form id="mission-form" novalidate>'+(i===0?profile():i===1?site():i===2?'<div id="garage"></div><input type="hidden" name="model" value=""><div id="machine-stats"></div>':i===3?team():i===4?plan():i===5?visit():referrals())+'<p class="game-error" id="game-error" role="alert"></p><div class="game-buttons"><button class="text-btn" type="button" id="game-back" '+(i===0?'hidden':'')+'>← Back</button><button class="btn gold" type="submit">'+(i===6?'Complete my mission':i===2?'Add to my mission':'Unlock next move')+' <span>→</span></button></div></form>';
 if(i===2){modelIndex=Math.max(0,MODELS.findIndex(m=>m.id===(state.answers.model||preferred(state.answers))));garage(false)}
 if(i===5){const date=$('[name=date]');const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());date.min=d.toISOString().slice(0,10)}
 $('#mission-form').addEventListener('input',()=>{state.answers={...state.answers,...collect()};if(i===0)updateMap();if(i===5)$('#visit-fields').hidden=!state.answers.visit||state.answers.visit==='Later';save()});
 $('#mission-form').addEventListener('submit',e=>{e.preventDefault();const patch=collect();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}const r=complete(state,i,patch);if(r.error){if(Number.isInteger(r.step)){state.step=r.step;render();focusStage()}$('#game-error').textContent=r.error;return}state=r.state;save();render();focusStage();if(r.earned)celebrate(i)});
 $('#game-back')?.addEventListener('click',()=>{state.answers={...state.answers,...collect()};state.step=Math.max(0,i-1);save();render();focusStage()});
 }
 function garage(animate,prevIndex){
 const m=MODELS[modelIndex],a=state.answers,old=MODELS[prevIndex];
 $('#garage').innerHTML='<div class="garage"><div class="garage-head"><span>THE EQUIPMENT GARAGE</span><b>0'+(modelIndex+1)+' / 03</b></div><div class="machine-photo"><img src="./assets/'+m.image+'" alt="Official Atlas Copco '+m.name+' product photograph" draggable="false"></div><div class="garage-name"><h4>'+m.name+'</h4><p>'+m.tag+'</p></div><div class="garage-nav"><button type="button" id="machine-prev" aria-label="Previous machine" '+(modelIndex===0?'disabled':'')+'>←</button><div class="garage-dots" role="group" aria-label="Select machine">'+MODELS.map((x,i)=>'<button type="button" data-model="'+i+'" aria-label="'+x.name+'" aria-pressed="'+(i===modelIndex)+'"></button>').join('')+'</div><button type="button" id="machine-next" aria-label="Higher capacity machine" '+(modelIndex===2?'disabled':'')+'>→</button></div></div>';
 $('[name=model]').value=m.id;state.answers.model=m.id;
 const delta=old?(m.flow-old.flow):0;
 $('#machine-stats').innerHTML='<div class="upgrade" role="status">'+(delta>0?'↗ CAPACITY UP · +'+delta+' cfm ('+Math.round(delta/old.flow*100)+'% more flow)':delta<0?'↙ A more compact capacity option':m.note)+'</div><div class="stat-grid"><div><span>FREE AIR DELIVERY AT 100 PSI</span><strong>'+m.flow+'<small>cfm</small></strong><div class="stat-meter" aria-label="'+m.flow+' cfm out of the 400 cfm comparison range">'+Array.from({length:20},(_,i)=>'<i class="'+(i<Math.round(m.flow/400*20)?'lit':'')+'"></i>').join('')+'</div></div><div><span>WORKING PRESSURE</span><strong>'+m.pressure+'<small>psi</small></strong><div class="stat-meter">'+Array.from({length:20},(_,i)=>'<i class="'+(i<(m.id==='400'?20:13)?'lit':'')+'"></i>').join('')+'</div></div></div><div class="fit-note">'+esc(fit(a,m))+'</div><p class="spec-source">'+m.engine+' · Diesel · <a href="'+m.url+'" target="_blank" rel="noopener">Manufacturer specifications ↗</a><br>Capacity is not an efficiency or quality score. More air is useful only if the job needs it. Photo may show optional equipment.</p>';
 const change=j=>{if(j<0||j>2||j===modelIndex)return;const previous=modelIndex;modelIndex=j;garage(true,previous);save()};
 $('#machine-prev').addEventListener('click',()=>change(modelIndex-1));$('#machine-next').addEventListener('click',()=>change(modelIndex+1));document.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>change(Number(b.dataset.model))));
 let start;const surface=$('.garage');surface.addEventListener('pointerdown',e=>{if(!e.target.closest('button'))start={x:e.clientX,y:e.clientY}});surface.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3)change(modelIndex+(dx<0?1:-1))});surface.addEventListener('pointercancel',()=>start=null);
 if(animate&&!paused()){$('.machine-photo img').animate([{transform:'translateX('+(modelIndex>prevIndex?'90':'-90')+'px) scale(.82)',opacity:0,filter:'blur(8px)'},{transform:'translateX(-6px) scale(1.03)',opacity:1,filter:'blur(0)'},{transform:'none',opacity:1}],{duration:700,easing:'cubic-bezier(.16,1,.3,1)'});document.querySelectorAll('.stat-meter .lit').forEach((el,i)=>el.animate([{opacity:.1,transform:'scaleY(.2)'},{opacity:1,transform:'scaleY(1)'}],{duration:400,delay:i*20,fill:'both'}))}
 }
 function result(){const a=state.answers,m=MODELS.find(x=>x.id===a.model)||MODELS[1];if(!state.code){state.code='AIR-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase();save()}
 $('#stage-eyebrow').textContent='MISSION COMPLETE / 07 OF 07';$('#stage-reward').textContent='1,000 XP · LEVEL 04';
 const summary=[['Your company',a.company],['Equipment to discuss',m.name],['Your path',a.intent+' · '+a.timeframe],['Decision role',a.authority],['Budget approver',a.approver||'Rep to identify'],['Purchasing',a.purchasing],['Walkthrough',a.visit==='Later'?'Discuss later':a.visit+' · '+a.date+' · '+a.slot+' · '+a.timezone],['Next contact',a.contact+' · '+(a.contact==='Email'?a.email:a.phone)]];
 $('#game-stage').innerHTML='<div class="result-hero"><div class="result-seal">✦</div><h3>'+esc(first())+', mission ready.</h3><p>Your next conversation starts with context.</p><div class="result-badges">'+STEPS.map(s=>'<span>✓ '+s.badge+'</span>').join('')+'</div></div><div class="garage"><div class="machine-photo"><img src="./assets/'+m.image+'" alt="'+m.name+'"></div><div class="garage-name"><h4>'+m.name+'</h4><p>'+m.flow+' cfm · '+m.pressure+' psi · Selected for discussion</p></div></div><div class="fit-note">'+esc(fit(a,m))+'</div><div class="mission-summary">'+summary.map(([k,v])=>'<div><small>'+k+'</small><strong>'+esc(v)+'</strong></div>').join('')+'</div><button id="mission-handoff" class="btn gold">'+(state.id?'Update my local sales record':'Create my local sales record')+' <span>→</span></button><p class="form-hint">Your details appear in the demo control room on this device. Walkthrough preferences are not a confirmed booking. No message is sent.</p><div class="share-options"><h4>Bring your team into the mission.</h4><p>Invite a teammate or another business. Your invitation link carries an anonymous referral code, never your name or email.</p><div class="actions"><button class="btn" id="share-invite">Share invitation ↗</button><button class="text-btn" id="copy-invite">Copy referral link</button><button class="text-btn" id="download-brief">Download my private brief ↓</button></div><input class="share-url" aria-label="Your referral invitation link" readonly value="'+publicLink(state.code)+'"><p>Your private brief includes the details you entered. Review it before forwarding. Invitation attribution is demonstrated locally when the link is opened; no cross-device referral reporting is connected.</p></div><button class="text-btn" id="review-answers" style="margin-top:20px">Review my answers ←</button>';
 $('#mission-handoff').addEventListener('click',()=>{state.id=handoff(state);save();go(3);toast('Your mission is in the local control room with an owner and next action.')});
 $('#copy-invite').addEventListener('click',()=>copy(publicLink(state.code),'Invitation link copied. Your personal details are not in the link.'));
 $('#share-invite').addEventListener('click',()=>share(publicLink(state.code),'Explore your Portable Air mission'));
 $('#download-brief').addEventListener('click',()=>{const blob=new Blob([briefing(state)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-portable-air-mission.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Private brief downloaded. It includes your contact and project details.')});
 $('#review-answers').addEventListener('click',()=>{state.step=0;save();render();focusStage()});
 }
 async function copy(text,message){try{await navigator.clipboard.writeText(text);toast(message)}catch{toast('Select and copy the invitation link shown below the buttons.')}}
 async function share(url,title){try{if(navigator.share){await navigator.share({title,text:'Build a Portable Air mission and explore the equipment.',url});return}await copy(url,'Invitation link copied.')}catch(e){if(e.name!=='AbortError')toast('Use Copy referral link to share this invitation.')}}
 $('#mission-map').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(!b)return;state.answers={...state.answers,...collect()};state.step=Number(b.dataset.step);save();render();focusStage()});
 $('#restart-mission').addEventListener('click',()=>{if(!confirm('Clear the mission details and its local sales record from this device?'))return;onClear(state.id);state=blank();save();render();toast('Your local mission details have been cleared.')});
 render();
}
